export const DIET_FILTERS = [
    'balanced',
    'high-fiber',
    'high-protein',
    'low-carb',
    'low-fat',
    'low-sodium',
];
export const HEALTH_FILTERS =[
    'alcohol-coctail',
    'celery-free',
    'alcohol-free',
    'crustacean-free',
    'diary-free',
    'DASH',
    'egg-free',
    'fish-free',
    'fodmap-free',
    'gluten-free',
    'immuno-suportive',
    'keto-friendly',
    'kosher',
    'low-potassium',
    'low-sugar',
    'lupine-free',
    'mediterranean',
    'mollusk-free',
    'No-oil-added',
    'paleo',
    'peanut-free',
    'pecatarian',
    'pork-free',
    'red-meat-free',
    'sesame-free',
    'shelfish-free',
    'sugar-concious',
    'sulfite-free',
    'soy-free',
    'tree-nut-free',
    'vegan',
];
export const MEAL_FILTERS=[
    {title:'Breakfast',icon:require('./images/brekfast.webp')},
    {title:'Brunch',icon:require('./images/brunch.jpg')},
    {title:'Lunch',icon:require('./images/lunch.webp')},
    {title:'Dinner',icon:require('./images/dinner.png')},
    {title:'Snack',icon:require('./images/snack.jpg')},
    {title:'Teatime',icon:require('./images/teatime.jpg')},
];
export const DISH_FILTERS=[
    'alcohol coctail',
    'biscuits and cookies',
    'bread',
    'cereals',
    'condiments and sauces',
    'desserts',
    'drinks',
    'egg',
    'ice cream and custards',
    'main course',
    'pancakes',
    'pastry',
    'pies and tarts',
    'pizza',
    'preps',
    'preserve',
    'salad',
    'sandwiches',
    'seafood',
    'side dish',
    'soup',
    'special occasions',
    'starter',
    'sweets',

];
export const CUISINE_FILTERS=[
    'american',
    'british',
    'carbbean',
    'central europe',
    'french',
    'greek',
    'indian',
    'italian',
    'japanese',
    'korean',
    'kosher',
    'mediterranean',
    'mexican',
    'middle eastern',
    'nordic',
    'south american',
    'south east asian',
    'world',
];

